/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 12-mai-2023 10:41:41 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

DROP TABLE IF EXISTS `appointments` CASCADE
;

DROP TABLE IF EXISTS `clinics` CASCADE
;

DROP TABLE IF EXISTS `dosage_admin` CASCADE
;

DROP TABLE IF EXISTS `examinations` CASCADE
;

DROP TABLE IF EXISTS `invoices` CASCADE
;

DROP TABLE IF EXISTS `invoices_paid` CASCADE
;

DROP TABLE IF EXISTS `location` CASCADE
;

DROP TABLE IF EXISTS `pen_treatments` CASCADE
;

DROP TABLE IF EXISTS `pens` CASCADE
;

DROP TABLE IF EXISTS `pet_owners` CASCADE
;

DROP TABLE IF EXISTS `pet_stay` CASCADE
;

DROP TABLE IF EXISTS `pet_treatments` CASCADE
;

DROP TABLE IF EXISTS `pets` CASCADE
;

DROP TABLE IF EXISTS `staff` CASCADE
;

DROP TABLE IF EXISTS `supplies` CASCADE
;

DROP TABLE IF EXISTS `tr_requirements` CASCADE
;

DROP TABLE IF EXISTS `treatments` CASCADE
;


CREATE TABLE `appointments`
(
	`appointmentID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`ownerID` INT NOT NULL,
	`petID` INT NOT NULL,
	`dateTime` DATETIME NOT NULL,
	CONSTRAINT `PK_appointments` PRIMARY KEY (`appointmentID` ASC, `clinicID` ASC)
)

;

CREATE TABLE `clinics`
(
	`clinicID` INT NOT NULL AUTO_INCREMENT,
	`postcode` VARCHAR(6) NULL,
	`street` VARCHAR(30) NULL,
	`telephone` VARCHAR(20) NULL,
	`faxNumber` VARCHAR(20) NULL,
	CONSTRAINT `PK_clinics` PRIMARY KEY (`clinicID` ASC)
)

;

CREATE TABLE `dosage_admin`
(
	`supplyID` VARCHAR(12) NOT NULL,
	`dosage` FLOAT NOT NULL,
	`methodOfAdministration` VARCHAR(100) NOT NULL,
	`supplyType` ENUM('SURGICAL', 'NON SURGICAL', 'PHARMA') NOT NULL,
	CONSTRAINT `PK_dosage_admin` PRIMARY KEY (`supplyID` ASC)
)

;

CREATE TABLE `examinations`
(
	`examinationID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`dateTime` DATETIME NOT NULL,
	`staffID` INT NOT NULL,
	`petID` INT NOT NULL,
	`description` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_examinations` PRIMARY KEY (`examinationID` ASC, `clinicID` ASC)
)

;

CREATE TABLE `invoices`
(
	`invoiceID` INT NOT NULL AUTO_INCREMENT,
	`petID` INT NOT NULL,
	`ownerID` INT NOT NULL,
	`dateDue` DATE NOT NULL,
	`clinicID` INT NOT NULL,
	`paid` BOOL NOT NULL,
	`petTID` INT NOT NULL,
	`examinationID` INT NOT NULL,
	CONSTRAINT `PK_invoices` PRIMARY KEY (`invoiceID` ASC)
)

;

CREATE TABLE `invoices_paid`
(
	`invoicePID` INT NOT NULL,
	`datePaid` DATE NOT NULL,
	`paymentType` ENUM('CASH', 'CREDIT CARD', 'CHECK') NOT NULL,
	CONSTRAINT `PK_invoices_paid` PRIMARY KEY (`invoicePID` ASC)
)

;

CREATE TABLE `location`
(
	`street` VARCHAR(50) NOT NULL,
	`postcode` VARCHAR(6) NOT NULL,
	`area` VARCHAR(50) NOT NULL,
	`city` VARCHAR(50) NOT NULL,
    
	CONSTRAINT `PK_location` PRIMARY KEY (`street` ASC, `postcode` ASC)
)

;

CREATE TABLE `pen_treatments`
(
	`comments` VARCHAR(100) NOT NULL,
	`treatmentID` VARCHAR(10) NOT NULL,
	`stayID` INT NOT NULL,
	CONSTRAINT `PK_pen_treatments` PRIMARY KEY (`treatmentID` ASC, `stayID` ASC)
)

;

CREATE TABLE `pens`
(
	`penID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`capacity` INT NOT NULL,
	`availability` INT NOT NULL,
	`closed` BOOL NOT NULL,
	CONSTRAINT `PK_pens` PRIMARY KEY (`penID` ASC, `clinicID` ASC)
)

;

CREATE TABLE `pet_owners`
(
	`ownerID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`firstName` VARCHAR(30) NOT NULL,
	`lastName` VARCHAR(30) NOT NULL,
	`telephone` VARCHAR(11) NOT NULL,
	`street` VARCHAR(30) NOT NULL,
	`postcode` VARCHAR(6) NOT NULL,
	CONSTRAINT `PK_pet_owners` PRIMARY KEY (`ownerID` ASC, `clinicID` ASC)
)

;

CREATE TABLE `pet_stay`
(
	`stayID` INT NOT NULL,
	`petID` INT NOT NULL,
	`penID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`startDate` DATE NOT NULL,
	`endDate` DATE NOT NULL,
	`isolatedStay` BOOL NOT NULL DEFAULT 0,
	`completedStay` BOOL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_pet_stay` PRIMARY KEY (`stayID` ASC)
)

;

CREATE TABLE `pet_treatments`
(
	`petTID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`treatmentID` VARCHAR(10) NOT NULL,
	`examinationID` INT NOT NULL,
	`petID` INT NOT NULL,
	`treatmentQuantity` INT NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	`startDate` DATE NOT NULL,
	`endDate` DATE NOT NULL,
	`comments` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_pet_treatments` PRIMARY KEY (`petTID` ASC, `examinationID` ASC)
)

;

CREATE TABLE `pets`
(
	`petID` INT NOT NULL,
	`clinicID` INT NOT NULL,
	`ownerID` INT NOT NULL,
	`typeOfPet` ENUM('Bird', 'Dog') NOT NULL,
	`dateOfBirth` DATE NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	`dateRegistered` DATE NOT NULL,
	`currentStatus` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_pets` PRIMARY KEY (`petID` ASC, `clinicID` ASC)
)

;

CREATE TABLE `staff`
(
	`staffID` INT NOT NULL AUTO_INCREMENT,
	`clinicID` INT NOT NULL,
	`firstName` VARCHAR(30) NOT NULL,
	`lastName` VARCHAR(30) NOT NULL,
	`postcode` VARCHAR(6) NOT NULL,
	`telephone` VARCHAR(11) NOT NULL,
	`dateOfBirth` DATE NOT NULL,
	`gender` ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
	`position` ENUM('MANAGER', 'VET', 'JANITOR', 'ACCOUNTANT', 'SALES') NOT NULL,
	`salary` FLOAT NOT NULL,
	`ssn` VARCHAR(12) NOT NULL,
	`street` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_staff` PRIMARY KEY (`staffID` ASC, `clinicID` ASC)
)

;

CREATE TABLE `supplies`
(
	`supplyID` VARCHAR(12) NOT NULL,
	`supplyType` ENUM('') NOT NULL,
	`clinicID` INT NOT NULL,
	`name` VARCHAR(30) NOT NULL,
	`amountInStock` INT NOT NULL,
	`unitsAvailable` INT NOT NULL,
	`description` VARCHAR(100) NULL,
	`reorderCost` FLOAT NOT NULL,
	`reorderLevel` INT NOT NULL,
	`reorderQuantity` INT NOT NULL,
	CONSTRAINT `PK_supplies` PRIMARY KEY (`supplyID` ASC, `supplyType` ASC)
)

;

CREATE TABLE `tr_requirements`
(
	`number` INT NOT NULL,
	`treatmentID` VARCHAR(10) NOT NULL,
	`supplyID` VARCHAR(12) NOT NULL,
	`supplyType` ENUM('SURGICAL', 'NON SURGICAL', 'PHARMA') NOT NULL,
	`unitsRequired` INT NOT NULL,
	CONSTRAINT `PK_tr_requirements` PRIMARY KEY (`number` ASC, `treatmentID` ASC)
)

;

CREATE TABLE `treatments`
(
	`treatmentID` VARCHAR(10) NOT NULL,
	`price` FLOAT NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_treatments` PRIMARY KEY (`treatmentID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `appointments` 
 ADD INDEX `IXFK_appointments_clinics` (`clinicID` ASC)
;

ALTER TABLE `appointments` 
 ADD INDEX `IXFK_appointments_pet_owners` (`ownerID` ASC, `clinicID` ASC)
;

ALTER TABLE `appointments` 
 ADD INDEX `IXFK_appointments_pets` (`petID` ASC, `clinicID` ASC)
;

ALTER TABLE `clinics` 
 ADD INDEX `IXFK_clinics_location` (`street` ASC, `postcode` ASC)
;

ALTER TABLE `dosage_admin` 
 ADD INDEX `IXFK_dosage_admin_supplies` (`supplyID` ASC, `supplyType` ASC)
;

ALTER TABLE `examinations` 
 ADD INDEX `IXFK_examinations_clinics` (`clinicID` ASC)
;


ALTER TABLE `examinations` 
 ADD INDEX `IXFK_examinations_pets` (`petID` ASC, `clinicID` ASC)
;


ALTER TABLE `examinations` 
 ADD INDEX `IXFK_examinations_staff` (`staffID` ASC, `clinicID` ASC)
;

ALTER TABLE `invoices` 
 ADD INDEX `IXFK_invoices_pet_owners` (`ownerID` ASC, `clinicID` ASC)
;

ALTER TABLE `invoices` 
 ADD INDEX `IXFK_invoices_pet_treatments` (`petTID` ASC, `examinationID` ASC)
;

ALTER TABLE `invoices` 
 ADD INDEX `IXFK_invoices_pets` (`petID` ASC, `clinicID` ASC)
;

ALTER TABLE `invoices_paid` 
 ADD INDEX `IXFK_invoices_paid_invoices` (`invoicePID` ASC)
;

ALTER TABLE `pen_treatments` 
 ADD INDEX `IXFK_pen_treatments_pet_stay` (`stayID` ASC)
;

ALTER TABLE `pen_treatments` 
 ADD INDEX `IXFK_pen_treatments_treatments` (`treatmentID` ASC)
;

ALTER TABLE `pens` 
 ADD INDEX `IXFK_pens_clinics` (`clinicID` ASC)
;

ALTER TABLE `pet_owners` 
 ADD INDEX `IXFK_pet_owners_clinics` (`clinicID` ASC)
;

ALTER TABLE `pet_owners` 
 ADD INDEX `IXFK_pet_owners_location` (`street` ASC, `postcode` ASC)
;

ALTER TABLE `pet_stay` 
 ADD INDEX `IXFK_pet_stay_pens` (`penID` ASC, `clinicID` ASC)
;

ALTER TABLE `pet_stay` 
 ADD INDEX `IXFK_pet_stay_pets` (`petID` ASC, `clinicID` ASC)
;

ALTER TABLE `pet_treatments` 
 ADD INDEX `IXFK_pet_treatments_clinics` (`clinicID` ASC)
;

ALTER TABLE `pet_treatments` 
 ADD INDEX `IXFK_pet_treatments_examinations` (`examinationID` ASC, `clinicID` ASC)
;

ALTER TABLE `pet_treatments` 
 ADD INDEX `IXFK_pet_treatments_pets` (`petID` ASC, `clinicID` ASC)
;

ALTER TABLE `pet_treatments` 
 ADD INDEX `IXFK_pet_treatments_treatments` (`treatmentID` ASC)
;

ALTER TABLE `pets` 
 ADD INDEX `IXFK_pets_clinics` (`clinicID` ASC)
;

ALTER TABLE `pets` 
 ADD INDEX `IXFK_pets_pet_owners` (`ownerID` ASC, `clinicID` ASC)
;

ALTER TABLE `staff` 
 ADD INDEX `IXFK_staff_clinics` (`clinicID` ASC)
;

ALTER TABLE `staff` 
 ADD INDEX `IXFK_staff_location` (`street` ASC, `postcode` ASC)
;

ALTER TABLE `supplies` 
 ADD INDEX `IXFK_supplies_clinics` (`clinicID` ASC)
;

ALTER TABLE `tr_requirements` 
 ADD INDEX `IXFK_tr_requirements_supplies` (`supplyID` ASC, `supplyType` ASC)
;

ALTER TABLE `tr_requirements` 
 ADD INDEX `IXFK_tr_requirements_treatments` (`treatmentID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `appointments` 
 ADD CONSTRAINT `FK_appointments_clinics`
	FOREIGN KEY (`clinicID`) REFERENCES `clinics` (`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `appointments` 
 ADD CONSTRAINT `FK_appointments_pet_owners`
	FOREIGN KEY (`ownerID`, `clinicID`) REFERENCES `pet_owners` (`ownerID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `appointments` 
 ADD CONSTRAINT `FK_appointments_pets`
	FOREIGN KEY (`petID`, `clinicID`) REFERENCES `pets` (`petID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `clinics` 
 ADD CONSTRAINT `FK_clinics_location`
	FOREIGN KEY (`street`, `postcode`) REFERENCES `location` (`street`,`postcode`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `dosage_admin` 
 ADD CONSTRAINT `FK_dosage_admin_supplies`
	FOREIGN KEY (`supplyID`, `supplyType`) REFERENCES `supplies` (`supplyID`,`supplyType`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `examinations` 
 ADD CONSTRAINT `FK_examinations_pets`
	FOREIGN KEY (`petID`, `clinicID`) REFERENCES `pets` (`petID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `examinations` 
 ADD CONSTRAINT `FK_examinations_staff`
	FOREIGN KEY (`staffID`, `clinicID`) REFERENCES `staff` (`staffID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `invoices` 
 ADD CONSTRAINT `FK_invoices_pet_owners`
	FOREIGN KEY (`ownerID`, `clinicID`) REFERENCES `pet_owners` (`ownerID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `invoices` 
 ADD CONSTRAINT `FK_invoices_pet_treatments`
	FOREIGN KEY (`petTID`, `examinationID`) REFERENCES `pet_treatments` (`petTID`,`examinationID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `invoices` 
 ADD CONSTRAINT `FK_invoices_pets`
	FOREIGN KEY (`petID`, `clinicID`) REFERENCES `pets` (`petID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pen_treatments` 
 ADD CONSTRAINT `FK_pen_treatments_pet_stay`
	FOREIGN KEY (`stayID`) REFERENCES `pet_stay` (`stayID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pen_treatments` 
 ADD CONSTRAINT `FK_pen_treatments_treatments`
	FOREIGN KEY (`treatmentID`) REFERENCES `treatments` (`treatmentID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pens` 
 ADD CONSTRAINT `FK_pens_clinics`
	FOREIGN KEY (`clinicID`) REFERENCES `clinics` (`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pet_owners` 
 ADD CONSTRAINT `FK_pet_owners_location`
	FOREIGN KEY (`street`, `postcode`) REFERENCES `location` (`street`,`postcode`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pet_stay` 
 ADD CONSTRAINT `FK_pet_stay_pens`
	FOREIGN KEY (`penID`, `clinicID`) REFERENCES `pens` (`penID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pet_stay` 
 ADD CONSTRAINT `FK_pet_stay_pets`
	FOREIGN KEY (`petID`, `clinicID`) REFERENCES `pets` (`petID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pet_treatments` 
 ADD CONSTRAINT `FK_pet_treatments_examinations`
	FOREIGN KEY (`examinationID`, `clinicID`) REFERENCES `examinations` (`examinationID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pet_treatments` 
 ADD CONSTRAINT `FK_pet_treatments_pets`
	FOREIGN KEY (`petID`, `clinicID`) REFERENCES `pets` (`petID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pet_treatments` 
 ADD CONSTRAINT `FK_pet_treatments_treatments`
	FOREIGN KEY (`treatmentID`) REFERENCES `treatments` (`treatmentID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pets` 
 ADD CONSTRAINT `FK_pets_clinics`
	FOREIGN KEY (`clinicID`) REFERENCES `clinics` (`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pets` 
 ADD CONSTRAINT `FK_pets_pet_owners`
	FOREIGN KEY (`ownerID`, `clinicID`) REFERENCES `pet_owners` (`ownerID`,`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `staff` 
 ADD CONSTRAINT `FK_staff_location`
	FOREIGN KEY (`street`, `postcode`) REFERENCES `location` (`street`,`postcode`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `supplies` 
 ADD CONSTRAINT `FK_supplies_clinics`
	FOREIGN KEY (`clinicID`) REFERENCES `clinics` (`clinicID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tr_requirements` 
 ADD CONSTRAINT `FK_tr_requirements_supplies`
	FOREIGN KEY (`supplyID`, `supplyType`) REFERENCES `supplies` (`supplyID`,`supplyType`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tr_requirements` 
 ADD CONSTRAINT `FK_tr_requirements_treatments`
	FOREIGN KEY (`treatmentID`) REFERENCES `treatments` (`treatmentID`) ON DELETE Restrict ON UPDATE Restrict
;


